### ISSUE TITLE
Keydown handler becomes unresponsive

### ISSUE THREAD

**Issue by ilpoo** [juhojo/corejumper#1]
Spamming navigation (right & left arrow keys) causes keydown handler to break.

**Comment by juhojo** [comment]
ReactTransitionGroup (RTG) allows canceling an animation which resets the view but does not re-trigger componentDidMount method which we originally used to set keybinds. This was solved using RTG's componentDidEnter method to re-ensure that the keybinds get reapplied when the animation is canceled.
