### ISSUE TITLE
Clicking on scrollbar track inaccurate

### ISSUE THREAD

**Issue by ilpoo** [juhojo/corejumper#10]
It currently tries to place the bottom of the scrollbar handle where you clicked on the the scrollbar track. Instead, it should calculate the percentage of the location you clicked relative to the track height and scroll the page by that percentage. This is how normal scrollbars work in Windows.

**Comment by juhojo** [comment]
Scrollbar's handle now gets positioned with percentages and then the content gets scrolled according to that percentage of the contents height. The handle gets positioned to center.

**Comment by juhojo** [comment]
We could try positioning the handle to top instead if it seems more user friendly (in short content such as Guide the handle seems to move quite a lot but in longer content such as Levels it looks fine as it is), but we can get back to this later.
