### ISSUE TITLE
Animating scrolling in levels

### ISSUE THREAD

**Issue by ilpoo** [juhojo/corejumper#3]
When the user uses up/down arrow keys or hovers over grid items, the grid is scrolled automatically to accommodate the newly selected grid item. This scrolling behaviour should be animated rather than instantaneous.

**Comment by juhojo** [comment]
The root of the problem originates to GSAP-plugin imports being poorly supported with webpack. Currently the default import only includes methods from TweenMax and to enable using plugins that are only included TweenLite, such as ScrollToPlugin, you need to make configurations (aliases more precisely) to webpack.config.js file. Plugin import problems should be resolved in the next GASP-package patch (current 1.19.0), see reference https://github.com/greensock/GreenSock-JS/issues/118.
